name: front-end-PR-workflow
on:
  pull_request:
    branches:
      - master
    types: [labeled]
jobs:
  dispatch_repo:
    runs-on: ubuntu-18.04
    if: github.event.label.name == 'ephemeral-deploy'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          #token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: OpenGov/cncf-demo-prep
          event-type: EKS-cluster
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "name" : "${{ github.event.pull_request.head.repo.name }}", "pull_number" : "${{ github.event.number }}", "target_branch_name" : "${{ github.base_ref }}", "branch_name" : "${{ github.head_ref }}"}'
    
